/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import common.PredefineMethods;
import inventory.Inventory;
import stores_and_packing.StoresPacking;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import maintenance.Maintenance;
import people.People;
import production.Process;

/**
 *
 * @author User
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        CurrDate.setText(PredefineMethods.getSystemDate());
        CurrTime.setText(PredefineMethods.getSystemTime());
    }
    
    void setColor(JPanel panel) { panel.setBackground(new Color(0, 165, 165));}

    void resetColor(JPanel panel) { panel.setBackground(new Color(0, 150, 150));}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Minimize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        CurrDate = new javax.swing.JLabel();
        CurrTime = new javax.swing.JLabel();
        Calender = new javax.swing.JLabel();
        Clock = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SidePanel = new javax.swing.JPanel();
        Production = new javax.swing.JPanel();
        DashboardImg1 = new javax.swing.JLabel();
        Dashboard1 = new javax.swing.JLabel();
        Inventory = new javax.swing.JPanel();
        DashboardImg5 = new javax.swing.JLabel();
        Dashboard5 = new javax.swing.JLabel();
        People = new javax.swing.JPanel();
        DashboardImg7 = new javax.swing.JLabel();
        Dashboard7 = new javax.swing.JLabel();
        DB = new javax.swing.JPanel();
        DashboardImg8 = new javax.swing.JLabel();
        Dashboard8 = new javax.swing.JLabel();
        SPL = new javax.swing.JPanel();
        DashboardImg9 = new javax.swing.JLabel();
        Dashboard9 = new javax.swing.JLabel();
        Dash = new javax.swing.JPanel();
        DashboardImg10 = new javax.swing.JLabel();
        Dashboard10 = new javax.swing.JLabel();
        TopPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Minimize1 = new javax.swing.JLabel();
        Close1 = new javax.swing.JLabel();
        CurrDate1 = new javax.swing.JLabel();
        CurrTime1 = new javax.swing.JLabel();
        Calender1 = new javax.swing.JLabel();
        Clock1 = new javax.swing.JLabel();
        un1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setBackground(new java.awt.Color(0, 102, 102));
        TopPanel.setMaximumSize(new java.awt.Dimension(1200, 130));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(103, 132));
        TopPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 63, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome..");
        TopPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 130, -1));

        jButton1.setBackground(new java.awt.Color(15, 195, 15));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Password.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TopPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 40, 40));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize.png"))); // NOI18N
        Minimize.setText("jLabel1");
        Minimize.setMaximumSize(new java.awt.Dimension(30, 30));
        Minimize.setMinimumSize(new java.awt.Dimension(30, 30));
        Minimize.setPreferredSize(new java.awt.Dimension(30, 30));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        TopPanel.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 30, 30));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        Close.setText("jLabel1");
        Close.setMaximumSize(new java.awt.Dimension(30, 30));
        Close.setMinimumSize(new java.awt.Dimension(30, 30));
        Close.setPreferredSize(new java.awt.Dimension(30, 30));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        TopPanel.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        CurrDate.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        CurrDate.setForeground(new java.awt.Color(255, 255, 255));
        CurrDate.setText("DATE");
        TopPanel.add(CurrDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 190, 30));

        CurrTime.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        CurrTime.setForeground(new java.awt.Color(255, 255, 255));
        CurrTime.setText("CLOCK");
        TopPanel.add(CurrTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 210, 30));

        Calender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calender.png"))); // NOI18N
        Calender.setText("jLabel1");
        Calender.setMaximumSize(new java.awt.Dimension(34, 30));
        Calender.setMinimumSize(new java.awt.Dimension(34, 30));
        Calender.setPreferredSize(new java.awt.Dimension(34, 30));
        TopPanel.add(Calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 34, 30));

        Clock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clock.png"))); // NOI18N
        Clock.setText("jLabel1");
        Clock.setMaximumSize(new java.awt.Dimension(34, 30));
        Clock.setMinimumSize(new java.awt.Dimension(34, 30));
        Clock.setPreferredSize(new java.awt.Dimension(34, 30));
        TopPanel.add(Clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 34, 30));

        un.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        un.setForeground(new java.awt.Color(255, 255, 255));
        TopPanel.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 130, 20));

        jButton2.setBackground(new java.awt.Color(219, 76, 13));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logout.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TopPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 40, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CACLogo.png"))); // NOI18N
        TopPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 130));

        getContentPane().add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 130));

        SidePanel.setBackground(new java.awt.Color(0, 102, 102));
        SidePanel.setMaximumSize(new java.awt.Dimension(260, 470));
        SidePanel.setMinimumSize(new java.awt.Dimension(260, 470));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Production.setBackground(new java.awt.Color(0, 150, 150));
        Production.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductionMouseExited(evt);
            }
        });

        DashboardImg1.setForeground(new java.awt.Color(255, 255, 255));
        DashboardImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Production.png"))); // NOI18N
        DashboardImg1.setText("jLabel1");
        DashboardImg1.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardImg1.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardImg1.setPreferredSize(new java.awt.Dimension(50, 40));

        Dashboard1.setBackground(new java.awt.Color(0, 150, 150));
        Dashboard1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Dashboard1.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard1.setText("Process");

        javax.swing.GroupLayout ProductionLayout = new javax.swing.GroupLayout(Production);
        Production.setLayout(ProductionLayout);
        ProductionLayout.setHorizontalGroup(
            ProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        ProductionLayout.setVerticalGroup(
            ProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Dashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidePanel.add(Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        Inventory.setBackground(new java.awt.Color(0, 150, 150));
        Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryMouseExited(evt);
            }
        });

        DashboardImg5.setForeground(new java.awt.Color(255, 255, 255));
        DashboardImg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventory.png"))); // NOI18N
        DashboardImg5.setText("jLabel1");
        DashboardImg5.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardImg5.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardImg5.setPreferredSize(new java.awt.Dimension(50, 40));

        Dashboard5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Dashboard5.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard5.setText("Inventory");

        javax.swing.GroupLayout InventoryLayout = new javax.swing.GroupLayout(Inventory);
        Inventory.setLayout(InventoryLayout);
        InventoryLayout.setHorizontalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardImg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        InventoryLayout.setVerticalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DashboardImg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dashboard5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidePanel.add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        People.setBackground(new java.awt.Color(0, 150, 150));
        People.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeopleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PeopleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PeopleMouseExited(evt);
            }
        });

        DashboardImg7.setForeground(new java.awt.Color(255, 255, 255));
        DashboardImg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/People.png"))); // NOI18N
        DashboardImg7.setText("jLabel1");
        DashboardImg7.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardImg7.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardImg7.setPreferredSize(new java.awt.Dimension(50, 40));

        Dashboard7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Dashboard7.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard7.setText("People");

        javax.swing.GroupLayout PeopleLayout = new javax.swing.GroupLayout(People);
        People.setLayout(PeopleLayout);
        PeopleLayout.setHorizontalGroup(
            PeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeopleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardImg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboard7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        PeopleLayout.setVerticalGroup(
            PeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DashboardImg7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dashboard7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidePanel.add(People, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        DB.setBackground(new java.awt.Color(0, 150, 150));
        DB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DBMouseExited(evt);
            }
        });

        DashboardImg8.setForeground(new java.awt.Color(255, 255, 255));
        DashboardImg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Maintanance.png"))); // NOI18N
        DashboardImg8.setText("jLabel1");
        DashboardImg8.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardImg8.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardImg8.setPreferredSize(new java.awt.Dimension(50, 40));

        Dashboard8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Dashboard8.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard8.setText("Maintenance");
        Dashboard8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DBLayout = new javax.swing.GroupLayout(DB);
        DB.setLayout(DBLayout);
        DBLayout.setHorizontalGroup(
            DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardImg8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboard8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        DBLayout.setVerticalGroup(
            DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DashboardImg8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dashboard8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidePanel.add(DB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        SPL.setBackground(new java.awt.Color(0, 150, 150));
        SPL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SPLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SPLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SPLMouseExited(evt);
            }
        });

        DashboardImg9.setForeground(new java.awt.Color(255, 255, 255));
        DashboardImg9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stores.png"))); // NOI18N
        DashboardImg9.setText("jLabel1");
        DashboardImg9.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardImg9.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardImg9.setPreferredSize(new java.awt.Dimension(50, 40));

        Dashboard9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Dashboard9.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard9.setText("Stores & Packing Lists");

        javax.swing.GroupLayout SPLLayout = new javax.swing.GroupLayout(SPL);
        SPL.setLayout(SPLLayout);
        SPLLayout.setHorizontalGroup(
            SPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardImg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboard9)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        SPLLayout.setVerticalGroup(
            SPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DashboardImg9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dashboard9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidePanel.add(SPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        Dash.setBackground(new java.awt.Color(0, 150, 150));
        Dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashMouseExited(evt);
            }
        });

        DashboardImg10.setForeground(new java.awt.Color(255, 255, 255));
        DashboardImg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard.png"))); // NOI18N
        DashboardImg10.setText("jLabel1");
        DashboardImg10.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardImg10.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardImg10.setPreferredSize(new java.awt.Dimension(50, 40));

        Dashboard10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Dashboard10.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard10.setText("Dashboard");

        javax.swing.GroupLayout DashLayout = new javax.swing.GroupLayout(Dash);
        Dash.setLayout(DashLayout);
        DashLayout.setHorizontalGroup(
            DashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardImg10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboard10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        DashLayout.setVerticalGroup(
            DashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DashboardImg10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dashboard10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SidePanel.add(Dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 480));

        TopPanel1.setBackground(new java.awt.Color(0, 102, 102));
        TopPanel1.setMaximumSize(new java.awt.Dimension(1200, 130));
        TopPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(103, 132));
        TopPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 63, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome !!!!!!");
        TopPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 130, -1));

        jButton3.setBackground(new java.awt.Color(15, 195, 15));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        TopPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 40, 40));

        Minimize1.setText("jLabel1");
        Minimize1.setMaximumSize(new java.awt.Dimension(30, 30));
        Minimize1.setMinimumSize(new java.awt.Dimension(30, 30));
        Minimize1.setPreferredSize(new java.awt.Dimension(30, 30));
        Minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimize1MouseClicked(evt);
            }
        });
        TopPanel1.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 30, 30));

        Close1.setText("jLabel1");
        Close1.setMaximumSize(new java.awt.Dimension(30, 30));
        Close1.setMinimumSize(new java.awt.Dimension(30, 30));
        Close1.setPreferredSize(new java.awt.Dimension(30, 30));
        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close1MouseClicked(evt);
            }
        });
        TopPanel1.add(Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 30, 30));

        CurrDate1.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        CurrDate1.setForeground(new java.awt.Color(255, 255, 255));
        CurrDate1.setText("DATE");
        TopPanel1.add(CurrDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 190, 30));

        CurrTime1.setFont(new java.awt.Font("BankGothic Md BT", 1, 20)); // NOI18N
        CurrTime1.setForeground(new java.awt.Color(255, 255, 255));
        CurrTime1.setText("CLOCK");
        TopPanel1.add(CurrTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 210, 30));

        Calender1.setText("jLabel1");
        Calender1.setMaximumSize(new java.awt.Dimension(34, 30));
        Calender1.setMinimumSize(new java.awt.Dimension(34, 30));
        Calender1.setPreferredSize(new java.awt.Dimension(34, 30));
        TopPanel1.add(Calender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 34, 30));

        Clock1.setText("jLabel1");
        Clock1.setMaximumSize(new java.awt.Dimension(34, 30));
        Clock1.setMinimumSize(new java.awt.Dimension(34, 30));
        Clock1.setPreferredSize(new java.awt.Dimension(34, 30));
        TopPanel1.add(Clock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 34, 30));

        un1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        un1.setForeground(new java.awt.Color(255, 255, 255));
        TopPanel1.add(un1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 130, 20));

        jButton4.setBackground(new java.awt.Color(219, 76, 13));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        TopPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 40, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TopPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 130));

        getContentPane().add(TopPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 130));

        DynamicPanel.setMaximumSize(new java.awt.Dimension(940, 480));
        DynamicPanel.setMinimumSize(new java.awt.Dimension(940, 480));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DynamicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 940, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
 
    }//GEN-LAST:event_MinimizeMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked

    }//GEN-LAST:event_CloseMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Login ob1 = new Login();
        ob1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ProductionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductionMouseClicked
        Process ob1 = new Process() {};
        BasicInternalFrameUI bi = (BasicInternalFrameUI)ob1.getUI();
        bi.setNorthPane(null);
        desktopPane.add(ob1).setVisible(true);
    }//GEN-LAST:event_ProductionMouseClicked

    private void ProductionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductionMouseEntered
        setColor(Production);
    }//GEN-LAST:event_ProductionMouseEntered

    private void ProductionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductionMouseExited
        resetColor(Production);
    }//GEN-LAST:event_ProductionMouseExited

    private void InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseClicked
        Inventory ob1 = new Inventory() {};
        BasicInternalFrameUI bi = (BasicInternalFrameUI)ob1.getUI();
        bi.setNorthPane(null);
        desktopPane.add(ob1).setVisible(true);
    }//GEN-LAST:event_InventoryMouseClicked

    private void InventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseEntered
        setColor(Inventory);
    }//GEN-LAST:event_InventoryMouseEntered

    private void InventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseExited
        resetColor(Inventory);
    }//GEN-LAST:event_InventoryMouseExited

    private void PeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeopleMouseClicked
        People ob1 = new People() {};
        BasicInternalFrameUI bi = (BasicInternalFrameUI)ob1.getUI();
        bi.setNorthPane(null);
        desktopPane.add(ob1).setVisible(true);
    }//GEN-LAST:event_PeopleMouseClicked

    private void PeopleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeopleMouseEntered
        setColor(People);
    }//GEN-LAST:event_PeopleMouseEntered

    private void PeopleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeopleMouseExited
        resetColor(People);
    }//GEN-LAST:event_PeopleMouseExited

    private void DBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DBMouseClicked
        Maintenance ob1 = new Maintenance();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)ob1.getUI();
        bi.setNorthPane(null);
        desktopPane.add(ob1).setVisible(true);
    }//GEN-LAST:event_DBMouseClicked

    private void DBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DBMouseEntered
        setColor(DB);
    }//GEN-LAST:event_DBMouseEntered

    private void DBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DBMouseExited
        resetColor(DB);
    }//GEN-LAST:event_DBMouseExited

    private void SPLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SPLMouseClicked
        StoresPacking ob1 = new StoresPacking();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)ob1.getUI();
        bi.setNorthPane(null);
        desktopPane.add(ob1).setVisible(true);
    }//GEN-LAST:event_SPLMouseClicked

    private void SPLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SPLMouseEntered
        setColor(SPL);
    }//GEN-LAST:event_SPLMouseEntered

    private void SPLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SPLMouseExited
        resetColor(SPL);
    }//GEN-LAST:event_SPLMouseExited

    private void DashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashMouseClicked
        Dashboard ob1 = new Dashboard();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)ob1.getUI();
        bi.setNorthPane(null);
        desktopPane.add(ob1).setVisible(true);
    }//GEN-LAST:event_DashMouseClicked

    private void DashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashMouseEntered
        setColor(Dash);
    }//GEN-LAST:event_DashMouseEntered

    private void DashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashMouseExited
        resetColor(Dash);
    }//GEN-LAST:event_DashMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize1MouseClicked
    
    }//GEN-LAST:event_Minimize1MouseClicked

    private void Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MouseClicked

    }//GEN-LAST:event_Close1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void Dashboard8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calender;
    private javax.swing.JLabel Calender1;
    private javax.swing.JLabel Clock;
    private javax.swing.JLabel Clock1;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel CurrDate;
    private javax.swing.JLabel CurrDate1;
    private javax.swing.JLabel CurrTime;
    private javax.swing.JLabel CurrTime1;
    private javax.swing.JPanel DB;
    private javax.swing.JPanel Dash;
    private javax.swing.JLabel Dashboard1;
    private javax.swing.JLabel Dashboard10;
    private javax.swing.JLabel Dashboard5;
    private javax.swing.JLabel Dashboard7;
    private javax.swing.JLabel Dashboard8;
    private javax.swing.JLabel Dashboard9;
    private javax.swing.JLabel DashboardImg1;
    private javax.swing.JLabel DashboardImg10;
    private javax.swing.JLabel DashboardImg5;
    private javax.swing.JLabel DashboardImg7;
    private javax.swing.JLabel DashboardImg8;
    private javax.swing.JLabel DashboardImg9;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel Inventory;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Minimize1;
    private javax.swing.JPanel People;
    private javax.swing.JPanel Production;
    private javax.swing.JPanel SPL;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel TopPanel1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel un;
    private javax.swing.JLabel un1;
    // End of variables declaration//GEN-END:variables
}
